/**
 * X3DH (Extended Triple Diffie-Hellman) key agreement.
 *
 * Establishes a shared secret between two parties using:
 *  - Identity keys (IK, long term X25519)
 *  - Signed prekeys (SPK, medium term X25519 signed with Ed25519 identity key)
 *  - Ephemeral keys (EK, one-time X25519 generated by the initiator)
 *  - One-time prekeys (OPK, optional one-time X25519)
 *
 * Reference: https://signal.org/docs/specifications/x3dh/
 */

import {
  KeyPair,
  generateX25519KeyPair,
  dh,
  hkdfDerive,
  concatBytes,
  utf8ToBytes,
  verify,
} from './keys';

// 32 bytes of 0xFF prefix, per X3DH spec, to avoid clashes with other protocols.
const X3DH_INFO = utf8ToBytes('AlloX3DH_CURVE25519_SHA256');
const KDF_PREFIX = new Uint8Array(32).fill(0xff);

/** Public prekey bundle fetched from the server for a peer. */
export interface PreKeyBundle {
  /** Ed25519 identity public key (used to verify the signed prekey). */
  identityKeyEd: Uint8Array;
  /** X25519 identity public key (used for DH). */
  identityKeyDh: Uint8Array;
  signedPreKey: {
    keyId: number;
    publicKey: Uint8Array;
    signature: Uint8Array;
  };
  /** Optional one-time prekey consumed from the server. */
  oneTimePreKey?: {
    keyId: number;
    publicKey: Uint8Array;
  };
}

export interface InitiatorResult {
  /** Derived 32-byte shared secret (root key seed). */
  sharedSecret: Uint8Array;
  /** Ephemeral public key the initiator generated (sent to the peer). */
  ephemeralPublicKey: Uint8Array;
  /** Signed prekey id used. */
  usedSignedPreKeyId: number;
  /** One-time prekey id used (if any). */
  usedOneTimePreKeyId?: number;
  /** Peer's signed prekey public (the receiver DH ratchet seed). */
  peerSignedPreKey: Uint8Array;
}

function kdf(dhConcat: Uint8Array): Uint8Array {
  const ikm = concatBytes(KDF_PREFIX, dhConcat);
  return hkdfDerive(ikm, new Uint8Array(32), X3DH_INFO, 32);
}

/**
 * Initiator side of X3DH. Verifies the signed prekey signature, then derives the
 * shared secret. Throws if the signed prekey signature is invalid.
 */
export function x3dhInitiate(
  identityKeyDh: KeyPair,
  bundle: PreKeyBundle
): InitiatorResult {
  // Verify signed prekey signature using the peer's Ed25519 identity key.
  const valid = verify(
    bundle.signedPreKey.signature,
    bundle.signedPreKey.publicKey,
    bundle.identityKeyEd
  );
  if (!valid) {
    throw new Error('X3DH: invalid signed prekey signature');
  }

  const ephemeral = generateX25519KeyPair();

  // DH1 = DH(IK_a, SPK_b)
  const dh1 = dh(identityKeyDh.privateKey, bundle.signedPreKey.publicKey);
  // DH2 = DH(EK_a, IK_b)
  const dh2 = dh(ephemeral.privateKey, bundle.identityKeyDh);
  // DH3 = DH(EK_a, SPK_b)
  const dh3 = dh(ephemeral.privateKey, bundle.signedPreKey.publicKey);

  let dhConcat = concatBytes(dh1, dh2, dh3);

  // DH4 = DH(EK_a, OPK_b) if a one-time prekey was provided.
  if (bundle.oneTimePreKey) {
    const dh4 = dh(ephemeral.privateKey, bundle.oneTimePreKey.publicKey);
    dhConcat = concatBytes(dhConcat, dh4);
  }

  const sharedSecret = kdf(dhConcat);

  return {
    sharedSecret,
    ephemeralPublicKey: ephemeral.publicKey,
    usedSignedPreKeyId: bundle.signedPreKey.keyId,
    usedOneTimePreKeyId: bundle.oneTimePreKey?.keyId,
    peerSignedPreKey: bundle.signedPreKey.publicKey,
  };
}

/** Local key material needed by the receiver to complete X3DH. */
export interface ReceiverKeys {
  identityKeyDh: KeyPair;
  signedPreKey: KeyPair;
  /** One-time prekey private key, looked up by id (optional). */
  oneTimePreKey?: KeyPair;
}

/** Header sent by the initiator that lets the receiver reconstruct the shared secret. */
export interface InitialMessageHeader {
  /** Initiator Ed25519 identity public key. */
  identityKeyEd: Uint8Array;
  /** Initiator X25519 identity public key. */
  identityKeyDh: Uint8Array;
  ephemeralKey: Uint8Array;
  usedSignedPreKeyId: number;
  usedOneTimePreKeyId?: number;
}

/**
 * Receiver side of X3DH. Reconstructs the shared secret from the initial header
 * and the receiver's own private keys.
 */
export function x3dhReceive(
  keys: ReceiverKeys,
  header: InitialMessageHeader
): Uint8Array {
  // DH1 = DH(SPK_b, IK_a)
  const dh1 = dh(keys.signedPreKey.privateKey, header.identityKeyDh);
  // DH2 = DH(IK_b, EK_a)
  const dh2 = dh(keys.identityKeyDh.privateKey, header.ephemeralKey);
  // DH3 = DH(SPK_b, EK_a)
  const dh3 = dh(keys.signedPreKey.privateKey, header.ephemeralKey);

  let dhConcat = concatBytes(dh1, dh2, dh3);

  if (header.usedOneTimePreKeyId !== undefined && keys.oneTimePreKey) {
    // DH4 = DH(OPK_b, EK_a)
    const dh4 = dh(keys.oneTimePreKey.privateKey, header.ephemeralKey);
    dhConcat = concatBytes(dhConcat, dh4);
  }

  return kdf(dhConcat);
}
