/**
 * The emoji the picker draws.
 *
 * Bloom ships no dataset on purpose — a full set with names and keywords is
 * tens of kilobytes that every app with its own would still pay for — so this
 * is Allo's, kept deliberately small: the glyphs a message actually reaches
 * for, grouped under the category keys Bloom's `EMOJI_CATEGORY_ICONS` already
 * has a glyph for (`smileys`, `people`, `animals`, `food`, `activity`,
 * `travel`, `objects`, `symbols`, `flags`).
 *
 * `name` and `keywords` are what Bloom's built-in search matches on, and they
 * are English only. Bloom's own note applies — emoji names are localised and a
 * translated set is a different dataset, not a translated string table — so
 * searching in Spanish or Italian finds nothing rather than pretending to. The
 * GROUP labels are not here: the composer takes those from `t()`, because those
 * nine strings are the ones a person actually reads.
 *
 * Data only. Nothing here imports anything but the type.
 */
import type { EmojiGroup } from '@oxy.so/bloom/chat-composer';

export const EMOJI_GROUPS: readonly EmojiGroup[] = [
  {
    key: 'smileys',
    label: 'Smileys and emotion',
    emojis: [
      { char: '😀', name: 'grinning face', keywords: ['smile', 'happy', 'grin'] },
      { char: '😃', name: 'grinning face with big eyes', keywords: ['smile', 'happy', 'joy'] },
      { char: '😄', name: 'grinning face with smiling eyes', keywords: ['smile', 'happy', 'joy', 'laugh'] },
      { char: '😁', name: 'beaming face with smiling eyes', keywords: ['grin', 'smile'] },
      { char: '😆', name: 'grinning squinting face', keywords: ['laugh', 'haha', 'satisfied'] },
      { char: '😅', name: 'grinning face with sweat', keywords: ['laugh', 'relief', 'nervous'] },
      { char: '🤣', name: 'rolling on the floor laughing', keywords: ['rofl', 'laugh', 'lol'] },
      { char: '😂', name: 'face with tears of joy', keywords: ['laugh', 'cry', 'lol'] },
      { char: '🙂', name: 'slightly smiling face', keywords: ['smile'] },
      { char: '🙃', name: 'upside-down face', keywords: ['silly', 'sarcasm'] },
      { char: '😉', name: 'winking face', keywords: ['wink', 'flirt'] },
      { char: '😊', name: 'smiling face with smiling eyes', keywords: ['blush', 'happy'] },
      { char: '😇', name: 'smiling face with halo', keywords: ['angel', 'innocent'] },
      { char: '🥰', name: 'smiling face with hearts', keywords: ['love', 'adore'] },
      { char: '😍', name: 'smiling face with heart-eyes', keywords: ['love', 'crush'] },
      { char: '🤩', name: 'star-struck', keywords: ['amazed', 'wow', 'star'] },
      { char: '😘', name: 'face blowing a kiss', keywords: ['kiss', 'love'] },
      { char: '😗', name: 'kissing face', keywords: ['kiss'] },
      { char: '😚', name: 'kissing face with closed eyes', keywords: ['kiss'] },
      { char: '😙', name: 'kissing face with smiling eyes', keywords: ['kiss'] },
      { char: '😋', name: 'face savoring food', keywords: ['yum', 'tasty', 'delicious'] },
      { char: '😛', name: 'face with tongue', keywords: ['tongue', 'silly'] },
      { char: '😜', name: 'winking face with tongue', keywords: ['tongue', 'silly', 'joke'] },
      { char: '🤪', name: 'zany face', keywords: ['crazy', 'silly', 'goofy'] },
      { char: '😝', name: 'squinting face with tongue', keywords: ['tongue', 'silly'] },
      { char: '🤑', name: 'money-mouth face', keywords: ['money', 'rich'] },
      { char: '🤗', name: 'smiling face with open hands', keywords: ['hug'] },
      { char: '🤭', name: 'face with hand over mouth', keywords: ['oops', 'giggle'] },
      { char: '🤫', name: 'shushing face', keywords: ['quiet', 'secret', 'shh'] },
      { char: '🤔', name: 'thinking face', keywords: ['think', 'hmm', 'consider'] },
      { char: '🤐', name: 'zipper-mouth face', keywords: ['quiet', 'secret'] },
      { char: '🤨', name: 'face with raised eyebrow', keywords: ['suspicious', 'skeptical'] },
      { char: '😐', name: 'neutral face', keywords: ['blank', 'meh'] },
      { char: '😑', name: 'expressionless face', keywords: ['blank'] },
      { char: '😶', name: 'face without mouth', keywords: ['silent', 'speechless'] },
      { char: '😏', name: 'smirking face', keywords: ['smirk', 'sly'] },
      { char: '😒', name: 'unamused face', keywords: ['annoyed', 'meh'] },
      { char: '🙄', name: 'face with rolling eyes', keywords: ['eyeroll', 'annoyed'] },
      { char: '😬', name: 'grimacing face', keywords: ['awkward', 'eek'] },
      { char: '🤥', name: 'lying face', keywords: ['liar', 'pinocchio'] },
      { char: '😌', name: 'relieved face', keywords: ['calm', 'content'] },
      { char: '😔', name: 'pensive face', keywords: ['sad', 'down'] },
      { char: '😪', name: 'sleepy face', keywords: ['tired'] },
      { char: '🤤', name: 'drooling face', keywords: ['drool'] },
      { char: '😴', name: 'sleeping face', keywords: ['sleep', 'zzz'] },
      { char: '😷', name: 'face with medical mask', keywords: ['sick', 'mask'] },
      { char: '🤒', name: 'face with thermometer', keywords: ['sick', 'fever'] },
      { char: '🤕', name: 'face with head-bandage', keywords: ['hurt', 'injured'] },
      { char: '🤢', name: 'nauseated face', keywords: ['sick', 'gross'] },
      { char: '🤮', name: 'face vomiting', keywords: ['sick', 'puke'] },
      { char: '🤧', name: 'sneezing face', keywords: ['sneeze', 'sick'] },
      { char: '🥵', name: 'hot face', keywords: ['heat', 'sweating'] },
      { char: '🥶', name: 'cold face', keywords: ['freezing'] },
      { char: '🥴', name: 'woozy face', keywords: ['dizzy', 'drunk'] },
      { char: '😵', name: 'face with crossed-out eyes', keywords: ['dizzy', 'knocked', 'out'] },
      { char: '🤯', name: 'exploding head', keywords: ['mind', 'blown', 'shocked'] },
      { char: '🤠', name: 'cowboy hat face', keywords: ['cowboy'] },
      { char: '🥳', name: 'partying face', keywords: ['party', 'celebrate', 'birthday'] },
      { char: '😎', name: 'smiling face with sunglasses', keywords: ['cool', 'sunglasses'] },
      { char: '🤓', name: 'nerd face', keywords: ['geek', 'glasses'] },
      { char: '🧐', name: 'face with monocle', keywords: ['inspect', 'curious'] },
      { char: '😕', name: 'confused face', keywords: ['unsure'] },
      { char: '😟', name: 'worried face', keywords: ['concerned'] },
      { char: '🙁', name: 'slightly frowning face', keywords: ['sad'] },
      { char: '😮', name: 'face with open mouth', keywords: ['surprised'] },
      { char: '😯', name: 'hushed face', keywords: ['surprised'] },
      { char: '😲', name: 'astonished face', keywords: ['shocked'] },
      { char: '😳', name: 'flushed face', keywords: ['embarrassed', 'blush'] },
      { char: '🥺', name: 'pleading face', keywords: ['beg', 'puppy', 'eyes'] },
      { char: '😦', name: 'frowning face with open mouth', keywords: ['sad'] },
      { char: '😧', name: 'anguished face', keywords: ['shocked'] },
      { char: '😨', name: 'fearful face', keywords: ['scared'] },
      { char: '😰', name: 'anxious face with sweat', keywords: ['nervous'] },
      { char: '😥', name: 'sad but relieved face', keywords: ['disappointed'] },
      { char: '😢', name: 'crying face', keywords: ['cry', 'sad', 'tear'] },
      { char: '😭', name: 'loudly crying face', keywords: ['sob', 'cry'] },
      { char: '😱', name: 'face screaming in fear', keywords: ['scream', 'shock'] },
      { char: '😖', name: 'confounded face', keywords: ['frustrated'] },
      { char: '😣', name: 'persevering face', keywords: ['struggle'] },
      { char: '😞', name: 'disappointed face', keywords: ['sad'] },
      { char: '😓', name: 'downcast face with sweat', keywords: ['sad', 'sweat'] },
      { char: '😩', name: 'weary face', keywords: ['tired', 'done'] },
      { char: '😫', name: 'tired face', keywords: ['exhausted'] },
      { char: '🥱', name: 'yawning face', keywords: ['bored', 'tired'] },
      { char: '😤', name: 'face with steam from nose', keywords: ['frustrated', 'triumph'] },
      { char: '😡', name: 'enraged face', keywords: ['angry', 'mad'] },
      { char: '😠', name: 'angry face', keywords: ['mad'] },
      { char: '🤬', name: 'face with symbols on mouth', keywords: ['swearing', 'cursing'] },
      { char: '😈', name: 'smiling face with horns', keywords: ['devil', 'mischief'] },
      { char: '👿', name: 'angry face with horns', keywords: ['devil', 'imp'] },
      { char: '💀', name: 'skull', keywords: ['dead'] },
      { char: '💩', name: 'pile of poo', keywords: ['poop'] },
      { char: '🤡', name: 'clown face', keywords: ['clown'] },
      { char: '👻', name: 'ghost', keywords: ['halloween', 'boo'] },
      { char: '👽', name: 'alien', keywords: ['ufo'] },
      { char: '🤖', name: 'robot', keywords: ['bot', 'android'] },
      { char: '😺', name: 'grinning cat', keywords: ['cat'] },
      { char: '😸', name: 'grinning cat with smiling eyes', keywords: ['cat'] },
      { char: '😹', name: 'cat with tears of joy', keywords: ['cat', 'laugh'] },
      { char: '😻', name: 'smiling cat with heart-eyes', keywords: ['cat', 'love'] },
      { char: '🙀', name: 'weary cat', keywords: ['cat', 'shock'] },
      { char: '😿', name: 'crying cat', keywords: ['cat', 'sad'] },
      { char: '💌', name: 'love letter', keywords: ['letter', 'heart'] },
      { char: '💘', name: 'heart with arrow', keywords: ['cupid', 'love'] },
      { char: '💝', name: 'heart with ribbon', keywords: ['gift', 'love'] },
      { char: '💖', name: 'sparkling heart', keywords: ['love'] },
      { char: '💗', name: 'growing heart', keywords: ['love'] },
      { char: '💓', name: 'beating heart', keywords: ['love'] },
      { char: '💞', name: 'revolving hearts', keywords: ['love'] },
      { char: '💕', name: 'two hearts', keywords: ['love'] },
      { char: '❤️', name: 'red heart', keywords: ['love'] },
      { char: '🧡', name: 'orange heart', keywords: ['love'] },
      { char: '💛', name: 'yellow heart', keywords: ['love'] },
      { char: '💚', name: 'green heart', keywords: ['love'] },
      { char: '💙', name: 'blue heart', keywords: ['love'] },
      { char: '💜', name: 'purple heart', keywords: ['love'] },
      { char: '🖤', name: 'black heart', keywords: ['love'] },
      { char: '🤍', name: 'white heart', keywords: ['love'] },
      { char: '🤎', name: 'brown heart', keywords: ['love'] },
      { char: '💔', name: 'broken heart', keywords: ['breakup', 'sad'] },
      { char: '❣️', name: 'heart exclamation', keywords: ['love'] },
      { char: '💯', name: 'hundred points', keywords: ['perfect', 'score'] },
      { char: '💥', name: 'collision', keywords: ['boom', 'explosion'] },
      { char: '💫', name: 'dizzy', keywords: ['stars'] },
      { char: '💦', name: 'sweat droplets', keywords: ['water', 'splash'] },
      { char: '💤', name: 'zzz', keywords: ['sleep'] },
    ],
  },
  {
    key: 'people',
    label: 'People and body',
    emojis: [
      { char: '👋', name: 'waving hand', keywords: ['wave', 'hello', 'bye'] },
      { char: '🤚', name: 'raised back of hand', keywords: ['hand'] },
      { char: '🖐️', name: 'hand with fingers splayed', keywords: ['hand'] },
      { char: '✋', name: 'raised hand', keywords: ['stop', 'high', 'five'] },
      { char: '🖖', name: 'vulcan salute', keywords: ['spock'] },
      { char: '👌', name: 'OK hand', keywords: ['ok', 'perfect'] },
      { char: '🤏', name: 'pinching hand', keywords: ['small', 'little'] },
      { char: '✌️', name: 'victory hand', keywords: ['peace'] },
      { char: '🤞', name: 'crossed fingers', keywords: ['luck', 'hope'] },
      { char: '🤟', name: 'love-you gesture', keywords: ['love'] },
      { char: '🤘', name: 'sign of the horns', keywords: ['rock'] },
      { char: '🤙', name: 'call me hand', keywords: ['shaka'] },
      { char: '👈', name: 'backhand index pointing left', keywords: ['point'] },
      { char: '👉', name: 'backhand index pointing right', keywords: ['point'] },
      { char: '👆', name: 'backhand index pointing up', keywords: ['point'] },
      { char: '👇', name: 'backhand index pointing down', keywords: ['point'] },
      { char: '☝️', name: 'index pointing up', keywords: ['point', 'one'] },
      { char: '👍', name: 'thumbs up', keywords: ['yes', 'like', 'approve'] },
      { char: '👎', name: 'thumbs down', keywords: ['no', 'dislike'] },
      { char: '✊', name: 'raised fist', keywords: ['fist', 'power'] },
      { char: '👊', name: 'oncoming fist', keywords: ['punch', 'bump'] },
      { char: '🤛', name: 'left-facing fist', keywords: ['bump'] },
      { char: '🤜', name: 'right-facing fist', keywords: ['bump'] },
      { char: '👏', name: 'clapping hands', keywords: ['clap', 'applause', 'bravo'] },
      { char: '🙌', name: 'raising hands', keywords: ['celebrate', 'praise'] },
      { char: '👐', name: 'open hands', keywords: ['hug'] },
      { char: '🤲', name: 'palms up together', keywords: ['pray', 'ask'] },
      { char: '🤝', name: 'handshake', keywords: ['deal', 'agreement'] },
      { char: '🙏', name: 'folded hands', keywords: ['pray', 'thanks', 'please'] },
      { char: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle'] },
      { char: '🦾', name: 'mechanical arm', keywords: ['prosthetic'] },
      { char: '🖕', name: 'middle finger', keywords: ['rude'] },
      { char: '✍️', name: 'writing hand', keywords: ['write'] },
      { char: '💅', name: 'nail polish', keywords: ['nails'] },
      { char: '🦵', name: 'leg', keywords: ['kick'] },
      { char: '🦶', name: 'foot', keywords: ['kick'] },
      { char: '👂', name: 'ear', keywords: ['hear', 'listen'] },
      { char: '👃', name: 'nose', keywords: ['smell'] },
      { char: '🧠', name: 'brain', keywords: ['smart', 'think'] },
      { char: '🦷', name: 'tooth', keywords: ['dentist'] },
      { char: '🦴', name: 'bone', keywords: ['skeleton'] },
      { char: '👀', name: 'eyes', keywords: ['look', 'see'] },
      { char: '👁️', name: 'eye', keywords: ['look'] },
      { char: '👄', name: 'mouth', keywords: ['lips'] },
      { char: '👶', name: 'baby', keywords: ['infant'] },
      { char: '🧒', name: 'child', keywords: ['kid'] },
      { char: '👦', name: 'boy', keywords: ['kid'] },
      { char: '👧', name: 'girl', keywords: ['kid'] },
      { char: '🧑', name: 'person', keywords: ['adult'] },
      { char: '👨', name: 'man', keywords: ['adult'] },
      { char: '👩', name: 'woman', keywords: ['adult'] },
      { char: '🧓', name: 'older person', keywords: ['elder'] },
      { char: '👴', name: 'old man', keywords: ['elder'] },
      { char: '👵', name: 'old woman', keywords: ['elder'] },
      { char: '🙍', name: 'person frowning', keywords: ['sad'] },
      { char: '🙎', name: 'person pouting', keywords: ['sulk'] },
      { char: '🙅', name: 'person gesturing NO', keywords: ['no', 'stop'] },
      { char: '🙆', name: 'person gesturing OK', keywords: ['ok', 'yes'] },
      { char: '💁', name: 'person tipping hand', keywords: ['sassy', 'information'] },
      { char: '🙋', name: 'person raising hand', keywords: ['question', 'volunteer'] },
      { char: '🙇', name: 'person bowing', keywords: ['sorry', 'respect'] },
      { char: '🤦', name: 'person facepalming', keywords: ['facepalm'] },
      { char: '🤷', name: 'person shrugging', keywords: ['shrug', 'idk'] },
      { char: '👮', name: 'police officer', keywords: ['cop'] },
      { char: '🕵️', name: 'detective', keywords: ['spy'] },
      { char: '💂', name: 'guard' },
      { char: '👷', name: 'construction worker', keywords: ['builder'] },
      { char: '🤴', name: 'prince', keywords: ['royal'] },
      { char: '👸', name: 'princess', keywords: ['royal'] },
      { char: '👰', name: 'person with veil', keywords: ['wedding', 'bride'] },
      { char: '🤵', name: 'person in tuxedo', keywords: ['wedding', 'groom'] },
      { char: '🎅', name: 'Santa Claus', keywords: ['christmas'] },
      { char: '🤶', name: 'Mrs. Claus', keywords: ['christmas'] },
      { char: '🦸', name: 'superhero', keywords: ['hero'] },
      { char: '🦹', name: 'supervillain', keywords: ['villain'] },
      { char: '🧙', name: 'mage', keywords: ['wizard'] },
      { char: '🧚', name: 'fairy' },
      { char: '🧛', name: 'vampire' },
      { char: '🧜', name: 'merperson', keywords: ['mermaid'] },
      { char: '🧝', name: 'elf' },
      { char: '🧞', name: 'genie' },
      { char: '🧟', name: 'zombie' },
      { char: '💆', name: 'person getting massage', keywords: ['spa'] },
      { char: '💇', name: 'person getting haircut', keywords: ['salon'] },
      { char: '🚶', name: 'person walking', keywords: ['walk'] },
      { char: '🧍', name: 'person standing', keywords: ['stand'] },
      { char: '🧎', name: 'person kneeling', keywords: ['kneel'] },
      { char: '🏃', name: 'person running', keywords: ['run'] },
      { char: '💃', name: 'woman dancing', keywords: ['dance'] },
      { char: '🕺', name: 'man dancing', keywords: ['dance'] },
      { char: '👯', name: 'people with bunny ears', keywords: ['party'] },
      { char: '🧖', name: 'person in steamy room', keywords: ['sauna'] },
      { char: '🧗', name: 'person climbing', keywords: ['climb'] },
      { char: '🤺', name: 'person fencing', keywords: ['fencing'] },
      { char: '🏇', name: 'horse racing', keywords: ['jockey'] },
      { char: '⛷️', name: 'skier', keywords: ['ski'] },
      { char: '🏂', name: 'snowboarder', keywords: ['snowboard'] },
      { char: '🏌️', name: 'person golfing', keywords: ['golf'] },
      { char: '🏄', name: 'person surfing', keywords: ['surf'] },
      { char: '🚣', name: 'person rowing boat', keywords: ['row'] },
      { char: '🏊', name: 'person swimming', keywords: ['swim'] },
      { char: '⛹️', name: 'person bouncing ball', keywords: ['basketball'] },
      { char: '🏋️', name: 'person lifting weights', keywords: ['gym'] },
      { char: '🚴', name: 'person biking', keywords: ['bike', 'cycle'] },
      { char: '🤸', name: 'person cartwheeling', keywords: ['gymnastics'] },
      { char: '🤼', name: 'people wrestling', keywords: ['wrestle'] },
      { char: '🤽', name: 'person playing water polo' },
      { char: '🤾', name: 'person playing handball' },
      { char: '🤹', name: 'person juggling', keywords: ['juggle'] },
      { char: '🧘', name: 'person in lotus position', keywords: ['yoga', 'meditate'] },
      { char: '🛀', name: 'person taking bath', keywords: ['bath'] },
      { char: '🛌', name: 'person in bed', keywords: ['sleep'] },
      { char: '👪', name: 'family' },
      { char: '🗣️', name: 'speaking head', keywords: ['talk'] },
      { char: '👤', name: 'bust in silhouette', keywords: ['user', 'person'] },
      { char: '👥', name: 'busts in silhouette', keywords: ['users', 'people'] },
      { char: '👣', name: 'footprints', keywords: ['steps'] },
    ],
  },
  {
    key: 'animals',
    label: 'Animals and nature',
    emojis: [
      { char: '🐶', name: 'dog face', keywords: ['puppy'] },
      { char: '🐱', name: 'cat face', keywords: ['kitten'] },
      { char: '🐭', name: 'mouse face' },
      { char: '🐹', name: 'hamster' },
      { char: '🐰', name: 'rabbit face', keywords: ['bunny'] },
      { char: '🦊', name: 'fox' },
      { char: '🐻', name: 'bear' },
      { char: '🐼', name: 'panda' },
      { char: '🐨', name: 'koala' },
      { char: '🐯', name: 'tiger face' },
      { char: '🦁', name: 'lion' },
      { char: '🐮', name: 'cow face' },
      { char: '🐷', name: 'pig face' },
      { char: '🐸', name: 'frog' },
      { char: '🐵', name: 'monkey face' },
      { char: '🙈', name: 'see-no-evil monkey', keywords: ['monkey'] },
      { char: '🙉', name: 'hear-no-evil monkey', keywords: ['monkey'] },
      { char: '🙊', name: 'speak-no-evil monkey', keywords: ['monkey'] },
      { char: '🐒', name: 'monkey' },
      { char: '🐔', name: 'chicken' },
      { char: '🐧', name: 'penguin' },
      { char: '🐦', name: 'bird' },
      { char: '🐤', name: 'baby chick' },
      { char: '🦆', name: 'duck' },
      { char: '🦅', name: 'eagle' },
      { char: '🦉', name: 'owl' },
      { char: '🦇', name: 'bat' },
      { char: '🐺', name: 'wolf' },
      { char: '🐗', name: 'boar' },
      { char: '🐴', name: 'horse face' },
      { char: '🦄', name: 'unicorn' },
      { char: '🐝', name: 'honeybee', keywords: ['bee'] },
      { char: '🐛', name: 'bug', keywords: ['caterpillar'] },
      { char: '🦋', name: 'butterfly' },
      { char: '🐌', name: 'snail' },
      { char: '🐞', name: 'lady beetle', keywords: ['ladybug'] },
      { char: '🐜', name: 'ant' },
      { char: '🕷️', name: 'spider' },
      { char: '🦂', name: 'scorpion' },
      { char: '🐢', name: 'turtle' },
      { char: '🐍', name: 'snake' },
      { char: '🦎', name: 'lizard' },
      { char: '🦖', name: 'T-Rex', keywords: ['dinosaur'] },
      { char: '🐙', name: 'octopus' },
      { char: '🦑', name: 'squid' },
      { char: '🦐', name: 'shrimp' },
      { char: '🦞', name: 'lobster' },
      { char: '🦀', name: 'crab' },
      { char: '🐡', name: 'blowfish' },
      { char: '🐠', name: 'tropical fish' },
      { char: '🐟', name: 'fish' },
      { char: '🐬', name: 'dolphin' },
      { char: '🐳', name: 'spouting whale', keywords: ['whale'] },
      { char: '🐋', name: 'whale' },
      { char: '🦈', name: 'shark' },
      { char: '🐊', name: 'crocodile' },
      { char: '🐅', name: 'tiger' },
      { char: '🦓', name: 'zebra' },
      { char: '🦍', name: 'gorilla' },
      { char: '🐘', name: 'elephant' },
      { char: '🦏', name: 'rhinoceros' },
      { char: '🐪', name: 'camel' },
      { char: '🦒', name: 'giraffe' },
      { char: '🐃', name: 'water buffalo' },
      { char: '🐄', name: 'cow' },
      { char: '🐖', name: 'pig' },
      { char: '🐑', name: 'ewe', keywords: ['sheep'] },
      { char: '🐐', name: 'goat' },
      { char: '🦌', name: 'deer' },
      { char: '🐕', name: 'dog' },
      { char: '🐩', name: 'poodle', keywords: ['dog'] },
      { char: '🦮', name: 'guide dog' },
      { char: '🐈', name: 'cat' },
      { char: '🐓', name: 'rooster' },
      { char: '🦃', name: 'turkey' },
      { char: '🦚', name: 'peacock' },
      { char: '🦜', name: 'parrot' },
      { char: '🦢', name: 'swan' },
      { char: '🐇', name: 'rabbit' },
      { char: '🦝', name: 'raccoon' },
      { char: '🦨', name: 'skunk' },
      { char: '🦥', name: 'sloth' },
      { char: '🐁', name: 'mouse' },
      { char: '🐿️', name: 'chipmunk' },
      { char: '🦔', name: 'hedgehog' },
      { char: '🌵', name: 'cactus' },
      { char: '🎄', name: 'Christmas tree', keywords: ['holiday'] },
      { char: '🌲', name: 'evergreen tree' },
      { char: '🌳', name: 'deciduous tree' },
      { char: '🌴', name: 'palm tree' },
      { char: '🌱', name: 'seedling', keywords: ['plant'] },
      { char: '🌿', name: 'herb' },
      { char: '☘️', name: 'shamrock' },
      { char: '🍀', name: 'four leaf clover', keywords: ['luck'] },
      { char: '🍁', name: 'maple leaf', keywords: ['autumn'] },
      { char: '🍂', name: 'fallen leaf', keywords: ['autumn'] },
      { char: '🍃', name: 'leaf fluttering in wind' },
      { char: '🍄', name: 'mushroom' },
      { char: '🌾', name: 'sheaf of rice' },
      { char: '💐', name: 'bouquet', keywords: ['flowers'] },
      { char: '🌷', name: 'tulip', keywords: ['flower'] },
      { char: '🌹', name: 'rose', keywords: ['flower'] },
      { char: '🥀', name: 'wilted flower' },
      { char: '🌺', name: 'hibiscus', keywords: ['flower'] },
      { char: '🌸', name: 'cherry blossom', keywords: ['sakura', 'flower'] },
      { char: '🌼', name: 'blossom', keywords: ['flower'] },
      { char: '🌻', name: 'sunflower' },
      { char: '🌞', name: 'sun with face', keywords: ['sunny'] },
      { char: '🌝', name: 'full moon face', keywords: ['moon'] },
      { char: '🌚', name: 'new moon face', keywords: ['moon'] },
      { char: '🌙', name: 'crescent moon', keywords: ['night'] },
      { char: '⭐', name: 'star' },
      { char: '🌟', name: 'glowing star', keywords: ['sparkle'] },
      { char: '✨', name: 'sparkles', keywords: ['shiny'] },
      { char: '⚡', name: 'high voltage', keywords: ['lightning'] },
      { char: '🔥', name: 'fire', keywords: ['lit', 'hot'] },
      { char: '🌈', name: 'rainbow' },
      { char: '☀️', name: 'sun', keywords: ['sunny'] },
      { char: '⛅', name: 'sun behind cloud', keywords: ['partly', 'cloudy'] },
      { char: '☁️', name: 'cloud', keywords: ['cloudy'] },
      { char: '🌧️', name: 'cloud with rain', keywords: ['rain'] },
      { char: '⛈️', name: 'cloud with lightning and rain', keywords: ['storm'] },
      { char: '❄️', name: 'snowflake', keywords: ['snow', 'cold'] },
      { char: '☃️', name: 'snowman', keywords: ['snow'] },
      { char: '💧', name: 'droplet', keywords: ['water'] },
      { char: '🌊', name: 'water wave', keywords: ['ocean', 'sea'] },
    ],
  },
  {
    key: 'food',
    label: 'Food and drink',
    emojis: [
      { char: '🍏', name: 'green apple', keywords: ['fruit'] },
      { char: '🍎', name: 'red apple', keywords: ['fruit'] },
      { char: '🍐', name: 'pear', keywords: ['fruit'] },
      { char: '🍊', name: 'tangerine', keywords: ['orange', 'fruit'] },
      { char: '🍋', name: 'lemon', keywords: ['fruit'] },
      { char: '🍌', name: 'banana', keywords: ['fruit'] },
      { char: '🍉', name: 'watermelon', keywords: ['fruit'] },
      { char: '🍇', name: 'grapes', keywords: ['fruit'] },
      { char: '🍓', name: 'strawberry', keywords: ['fruit'] },
      { char: '🫐', name: 'blueberries', keywords: ['fruit'] },
      { char: '🍈', name: 'melon', keywords: ['fruit'] },
      { char: '🍒', name: 'cherries', keywords: ['fruit'] },
      { char: '🍑', name: 'peach', keywords: ['fruit'] },
      { char: '🥭', name: 'mango', keywords: ['fruit'] },
      { char: '🍍', name: 'pineapple', keywords: ['fruit'] },
      { char: '🥥', name: 'coconut' },
      { char: '🥝', name: 'kiwi fruit' },
      { char: '🍅', name: 'tomato' },
      { char: '🍆', name: 'eggplant', keywords: ['aubergine'] },
      { char: '🥑', name: 'avocado' },
      { char: '🥦', name: 'broccoli' },
      { char: '🥬', name: 'leafy green', keywords: ['lettuce'] },
      { char: '🥒', name: 'cucumber' },
      { char: '🌶️', name: 'hot pepper', keywords: ['spicy', 'chili'] },
      { char: '🌽', name: 'ear of corn' },
      { char: '🥕', name: 'carrot' },
      { char: '🧄', name: 'garlic' },
      { char: '🧅', name: 'onion' },
      { char: '🥔', name: 'potato' },
      { char: '🍠', name: 'roasted sweet potato' },
      { char: '🥐', name: 'croissant' },
      { char: '🥖', name: 'baguette bread' },
      { char: '🍞', name: 'bread' },
      { char: '🥨', name: 'pretzel' },
      { char: '🧀', name: 'cheese wedge', keywords: ['cheese'] },
      { char: '🥚', name: 'egg' },
      { char: '🍳', name: 'cooking', keywords: ['fried', 'egg', 'breakfast'] },
      { char: '🥞', name: 'pancakes' },
      { char: '🧇', name: 'waffle' },
      { char: '🥓', name: 'bacon' },
      { char: '🥩', name: 'cut of meat', keywords: ['steak'] },
      { char: '🍗', name: 'poultry leg', keywords: ['chicken'] },
      { char: '🍖', name: 'meat on bone' },
      { char: '🌭', name: 'hot dog' },
      { char: '🍔', name: 'hamburger', keywords: ['burger'] },
      { char: '🍟', name: 'french fries', keywords: ['fries'] },
      { char: '🍕', name: 'pizza' },
      { char: '🥪', name: 'sandwich' },
      { char: '🌮', name: 'taco' },
      { char: '🌯', name: 'burrito' },
      { char: '🥗', name: 'green salad', keywords: ['salad'] },
      { char: '🥘', name: 'shallow pan of food', keywords: ['paella'] },
      { char: '🍝', name: 'spaghetti', keywords: ['pasta'] },
      { char: '🍜', name: 'steaming bowl', keywords: ['ramen', 'noodles'] },
      { char: '🍲', name: 'pot of food', keywords: ['stew'] },
      { char: '🍛', name: 'curry rice' },
      { char: '🍣', name: 'sushi' },
      { char: '🍱', name: 'bento box' },
      { char: '🥟', name: 'dumpling' },
      { char: '🍤', name: 'fried shrimp', keywords: ['tempura'] },
      { char: '🍚', name: 'cooked rice' },
      { char: '🍙', name: 'rice ball', keywords: ['onigiri'] },
      { char: '🍥', name: 'fish cake with swirl' },
      { char: '🥠', name: 'fortune cookie' },
      { char: '🍦', name: 'soft ice cream' },
      { char: '🍧', name: 'shaved ice' },
      { char: '🍨', name: 'ice cream' },
      { char: '🍩', name: 'doughnut', keywords: ['donut'] },
      { char: '🍪', name: 'cookie' },
      { char: '🎂', name: 'birthday cake', keywords: ['cake'] },
      { char: '🍰', name: 'shortcake', keywords: ['cake'] },
      { char: '🧁', name: 'cupcake' },
      { char: '🥧', name: 'pie' },
      { char: '🍫', name: 'chocolate bar' },
      { char: '🍬', name: 'candy', keywords: ['sweet'] },
      { char: '🍭', name: 'lollipop' },
      { char: '🍯', name: 'honey pot', keywords: ['honey'] },
      { char: '🍼', name: 'baby bottle', keywords: ['milk'] },
      { char: '🥛', name: 'glass of milk', keywords: ['milk'] },
      { char: '☕', name: 'hot beverage', keywords: ['coffee', 'tea'] },
      { char: '🍵', name: 'teacup without handle', keywords: ['tea'] },
      { char: '🧃', name: 'beverage box', keywords: ['juice'] },
      { char: '🥤', name: 'cup with straw', keywords: ['soda'] },
      { char: '🍺', name: 'beer mug', keywords: ['beer'] },
      { char: '🍻', name: 'clinking beer mugs', keywords: ['cheers'] },
      { char: '🥂', name: 'clinking glasses', keywords: ['cheers', 'champagne'] },
      { char: '🍷', name: 'wine glass', keywords: ['wine'] },
      { char: '🥃', name: 'tumbler glass', keywords: ['whisky'] },
      { char: '🍸', name: 'cocktail glass', keywords: ['martini'] },
      { char: '🍹', name: 'tropical drink', keywords: ['cocktail'] },
      { char: '🍾', name: 'bottle with popping cork', keywords: ['champagne', 'celebrate'] },
      { char: '🧊', name: 'ice' },
      { char: '🍽️', name: 'fork and knife with plate', keywords: ['dinner', 'eat'] },
      { char: '🥄', name: 'spoon' },
    ],
  },
  {
    key: 'activity',
    label: 'Activity',
    emojis: [
      { char: '⚽', name: 'soccer ball', keywords: ['football'] },
      { char: '🏀', name: 'basketball' },
      { char: '🏈', name: 'american football' },
      { char: '⚾', name: 'baseball' },
      { char: '🥎', name: 'softball' },
      { char: '🎾', name: 'tennis' },
      { char: '🏐', name: 'volleyball' },
      { char: '🏉', name: 'rugby football' },
      { char: '🥏', name: 'flying disc', keywords: ['frisbee'] },
      { char: '🎱', name: 'pool 8 ball', keywords: ['billiards'] },
      { char: '🏓', name: 'ping pong', keywords: ['table', 'tennis'] },
      { char: '🏸', name: 'badminton' },
      { char: '🥅', name: 'goal net' },
      { char: '🏒', name: 'ice hockey' },
      { char: '🏑', name: 'field hockey' },
      { char: '🥍', name: 'lacrosse' },
      { char: '🏏', name: 'cricket game' },
      { char: '⛳', name: 'flag in hole', keywords: ['golf'] },
      { char: '🏹', name: 'bow and arrow', keywords: ['archery'] },
      { char: '🎣', name: 'fishing pole', keywords: ['fishing'] },
      { char: '🥊', name: 'boxing glove', keywords: ['boxing'] },
      { char: '🥋', name: 'martial arts uniform', keywords: ['karate', 'judo'] },
      { char: '🎽', name: 'running shirt' },
      { char: '🛹', name: 'skateboard' },
      { char: '🛼', name: 'roller skate' },
      { char: '🛷', name: 'sled' },
      { char: '⛸️', name: 'ice skate', keywords: ['skating'] },
      { char: '🥌', name: 'curling stone' },
      { char: '🎿', name: 'skis', keywords: ['ski'] },
      { char: '⛺', name: 'tent', keywords: ['camping'] },
      { char: '🎪', name: 'circus tent' },
      { char: '🎭', name: 'performing arts', keywords: ['theatre', 'drama'] },
      { char: '🎨', name: 'artist palette', keywords: ['art', 'paint'] },
      { char: '🎬', name: 'clapper board', keywords: ['movie', 'film'] },
      { char: '🎤', name: 'microphone', keywords: ['sing', 'karaoke'] },
      { char: '🎧', name: 'headphone', keywords: ['music', 'listen'] },
      { char: '🎼', name: 'musical score', keywords: ['music'] },
      { char: '🎹', name: 'musical keyboard', keywords: ['piano'] },
      { char: '🥁', name: 'drum' },
      { char: '🎷', name: 'saxophone' },
      { char: '🎺', name: 'trumpet' },
      { char: '🎸', name: 'guitar' },
      { char: '🪕', name: 'banjo' },
      { char: '🎻', name: 'violin' },
      { char: '🎲', name: 'game die', keywords: ['dice'] },
      { char: '♟️', name: 'chess pawn', keywords: ['chess'] },
      { char: '🎯', name: 'bullseye', keywords: ['dart', 'target'] },
      { char: '🎳', name: 'bowling' },
      { char: '🎮', name: 'video game', keywords: ['gaming', 'controller'] },
      { char: '🕹️', name: 'joystick', keywords: ['gaming'] },
      { char: '🎰', name: 'slot machine', keywords: ['casino'] },
      { char: '🧩', name: 'puzzle piece', keywords: ['jigsaw'] },
      { char: '🎈', name: 'balloon', keywords: ['party'] },
      { char: '🎉', name: 'party popper', keywords: ['celebrate', 'congrats'] },
      { char: '🎊', name: 'confetti ball', keywords: ['celebrate'] },
      { char: '🎁', name: 'wrapped gift', keywords: ['present'] },
      { char: '🎀', name: 'ribbon' },
      { char: '🏆', name: 'trophy', keywords: ['win', 'award'] },
      { char: '🥇', name: '1st place medal', keywords: ['gold', 'win'] },
      { char: '🥈', name: '2nd place medal', keywords: ['silver'] },
      { char: '🥉', name: '3rd place medal', keywords: ['bronze'] },
      { char: '🏅', name: 'sports medal', keywords: ['award'] },
      { char: '🎖️', name: 'military medal', keywords: ['award'] },
    ],
  },
  {
    key: 'travel',
    label: 'Travel and places',
    emojis: [
      { char: '🚗', name: 'automobile', keywords: ['car'] },
      { char: '🚕', name: 'taxi' },
      { char: '🚙', name: 'sport utility vehicle', keywords: ['suv', 'car'] },
      { char: '🚌', name: 'bus' },
      { char: '🚎', name: 'trolleybus' },
      { char: '🏎️', name: 'racing car', keywords: ['race'] },
      { char: '🚓', name: 'police car' },
      { char: '🚑', name: 'ambulance' },
      { char: '🚒', name: 'fire engine' },
      { char: '🚐', name: 'minibus', keywords: ['van'] },
      { char: '🚚', name: 'delivery truck' },
      { char: '🚛', name: 'articulated lorry', keywords: ['truck'] },
      { char: '🚜', name: 'tractor' },
      { char: '🛵', name: 'motor scooter' },
      { char: '🏍️', name: 'motorcycle' },
      { char: '🛺', name: 'auto rickshaw', keywords: ['tuktuk'] },
      { char: '🚲', name: 'bicycle', keywords: ['bike'] },
      { char: '🛴', name: 'kick scooter' },
      { char: '🚨', name: 'police car light', keywords: ['siren', 'emergency'] },
      { char: '🚔', name: 'oncoming police car' },
      { char: '🚍', name: 'oncoming bus' },
      { char: '🚋', name: 'tram car' },
      { char: '🚆', name: 'train' },
      { char: '🚄', name: 'high-speed train', keywords: ['bullet', 'train'] },
      { char: '🚈', name: 'light rail' },
      { char: '🚇', name: 'metro', keywords: ['subway'] },
      { char: '🚊', name: 'tram' },
      { char: '🚝', name: 'monorail' },
      { char: '🚉', name: 'station' },
      { char: '✈️', name: 'airplane', keywords: ['flight', 'plane'] },
      { char: '🛫', name: 'airplane departure', keywords: ['takeoff'] },
      { char: '🛬', name: 'airplane arrival', keywords: ['landing'] },
      { char: '🛩️', name: 'small airplane' },
      { char: '🚁', name: 'helicopter' },
      { char: '🚀', name: 'rocket', keywords: ['launch', 'space'] },
      { char: '🛸', name: 'flying saucer', keywords: ['ufo'] },
      { char: '⛵', name: 'sailboat', keywords: ['sailing'] },
      { char: '🛥️', name: 'motor boat' },
      { char: '🚤', name: 'speedboat' },
      { char: '⛴️', name: 'ferry' },
      { char: '🚢', name: 'ship', keywords: ['cruise'] },
      { char: '⚓', name: 'anchor' },
      { char: '🚧', name: 'construction', keywords: ['roadwork'] },
      { char: '⛽', name: 'fuel pump', keywords: ['gas', 'petrol'] },
      { char: '🗺️', name: 'world map', keywords: ['map'] },
      { char: '🧭', name: 'compass', keywords: ['navigate'] },
      { char: '🗿', name: 'moai', keywords: ['statue'] },
      { char: '🗽', name: 'Statue of Liberty', keywords: ['new', 'york'] },
      { char: '🗼', name: 'Tokyo tower' },
      { char: '🏰', name: 'castle' },
      { char: '🏯', name: 'Japanese castle' },
      { char: '🏟️', name: 'stadium' },
      { char: '🎡', name: 'ferris wheel' },
      { char: '🎢', name: 'roller coaster' },
      { char: '🎠', name: 'carousel horse' },
      { char: '⛲', name: 'fountain' },
      { char: '⛱️', name: 'umbrella on ground', keywords: ['beach'] },
      { char: '🏖️', name: 'beach with umbrella', keywords: ['beach'] },
      { char: '🏝️', name: 'desert island', keywords: ['island'] },
      { char: '🏜️', name: 'desert' },
      { char: '🌋', name: 'volcano' },
      { char: '⛰️', name: 'mountain' },
      { char: '🏔️', name: 'snow-capped mountain' },
      { char: '🗻', name: 'mount fuji' },
      { char: '🏕️', name: 'camping' },
      { char: '🏠', name: 'house', keywords: ['home'] },
      { char: '🏡', name: 'house with garden', keywords: ['home'] },
      { char: '🏢', name: 'office building', keywords: ['work'] },
      { char: '🏥', name: 'hospital' },
      { char: '🏦', name: 'bank' },
      { char: '🏨', name: 'hotel' },
      { char: '🏫', name: 'school' },
      { char: '🏭', name: 'factory' },
      { char: '🏗️', name: 'building construction' },
      { char: '🕌', name: 'mosque' },
      { char: '🕍', name: 'synagogue' },
      { char: '⛪', name: 'church' },
      { char: '🛕', name: 'hindu temple' },
      { char: '🌃', name: 'night with stars', keywords: ['city', 'night'] },
      { char: '🌆', name: 'cityscape at dusk', keywords: ['city'] },
      { char: '🌇', name: 'sunset', keywords: ['city'] },
      { char: '🌉', name: 'bridge at night' },
      { char: '🌁', name: 'foggy', keywords: ['fog'] },
      { char: '🏙️', name: 'cityscape', keywords: ['city'] },
      { char: '🌌', name: 'milky way', keywords: ['stars', 'galaxy'] },
      { char: '🎑', name: 'moon viewing ceremony' },
    ],
  },
  {
    key: 'objects',
    label: 'Objects',
    emojis: [
      { char: '⌚', name: 'watch', keywords: ['time'] },
      { char: '📱', name: 'mobile phone', keywords: ['phone'] },
      { char: '💻', name: 'laptop', keywords: ['computer'] },
      { char: '⌨️', name: 'keyboard', keywords: ['typing'] },
      { char: '🖥️', name: 'desktop computer' },
      { char: '🖨️', name: 'printer' },
      { char: '🖱️', name: 'computer mouse' },
      { char: '💽', name: 'computer disk' },
      { char: '💾', name: 'floppy disk', keywords: ['save'] },
      { char: '💿', name: 'optical disk', keywords: ['cd'] },
      { char: '📀', name: 'dvd' },
      { char: '📷', name: 'camera', keywords: ['photo'] },
      { char: '📸', name: 'camera with flash', keywords: ['photo'] },
      { char: '📹', name: 'video camera' },
      { char: '🎥', name: 'movie camera', keywords: ['film'] },
      { char: '📞', name: 'telephone receiver', keywords: ['call'] },
      { char: '☎️', name: 'telephone', keywords: ['call'] },
      { char: '📟', name: 'pager' },
      { char: '📠', name: 'fax machine' },
      { char: '📺', name: 'television', keywords: ['tv'] },
      { char: '📻', name: 'radio' },
      { char: '🎙️', name: 'studio microphone', keywords: ['podcast'] },
      { char: '⏱️', name: 'stopwatch', keywords: ['timer'] },
      { char: '⏰', name: 'alarm clock', keywords: ['alarm'] },
      { char: '⏳', name: 'hourglass done', keywords: ['time', 'wait'] },
      { char: '🔋', name: 'battery' },
      { char: '🔌', name: 'electric plug' },
      { char: '💡', name: 'light bulb', keywords: ['idea'] },
      { char: '🔦', name: 'flashlight', keywords: ['torch'] },
      { char: '🕯️', name: 'candle' },
      { char: '🧯', name: 'fire extinguisher' },
      { char: '🛢️', name: 'oil drum' },
      { char: '💸', name: 'money with wings', keywords: ['spend', 'cash'] },
      { char: '💵', name: 'dollar banknote', keywords: ['money'] },
      { char: '💴', name: 'yen banknote', keywords: ['money'] },
      { char: '💶', name: 'euro banknote', keywords: ['money'] },
      { char: '💷', name: 'pound banknote', keywords: ['money'] },
      { char: '💰', name: 'money bag', keywords: ['cash', 'rich'] },
      { char: '💳', name: 'credit card', keywords: ['payment'] },
      { char: '🧾', name: 'receipt', keywords: ['invoice'] },
      { char: '💎', name: 'gem stone', keywords: ['diamond'] },
      { char: '⚖️', name: 'balance scale', keywords: ['justice', 'law'] },
      { char: '🔧', name: 'wrench', keywords: ['tool', 'fix'] },
      { char: '🔨', name: 'hammer', keywords: ['tool'] },
      { char: '🛠️', name: 'hammer and wrench', keywords: ['tools'] },
      { char: '⚙️', name: 'gear', keywords: ['settings', 'cog'] },
      { char: '🧲', name: 'magnet' },
      { char: '🔫', name: 'water pistol' },
      { char: '💣', name: 'bomb' },
      { char: '🧨', name: 'firecracker' },
      { char: '🔪', name: 'kitchen knife' },
      { char: '🚪', name: 'door' },
      { char: '🪑', name: 'chair', keywords: ['seat'] },
      { char: '🛏️', name: 'bed', keywords: ['sleep'] },
      { char: '🚿', name: 'shower' },
      { char: '🛁', name: 'bathtub' },
      { char: '🧹', name: 'broom', keywords: ['clean'] },
      { char: '🧺', name: 'basket', keywords: ['laundry'] },
      { char: '🧻', name: 'roll of paper', keywords: ['toilet', 'paper'] },
      { char: '🧼', name: 'soap', keywords: ['wash'] },
      { char: '🧽', name: 'sponge', keywords: ['clean'] },
      { char: '🔑', name: 'key' },
      { char: '🗝️', name: 'old key' },
      { char: '🔒', name: 'locked', keywords: ['lock', 'secure'] },
      { char: '🔓', name: 'unlocked', keywords: ['unlock'] },
      { char: '🔐', name: 'locked with key', keywords: ['secure'] },
      { char: '🔏', name: 'locked with pen', keywords: ['privacy'] },
      { char: '🛡️', name: 'shield', keywords: ['protect', 'security'] },
      { char: '🧬', name: 'dna', keywords: ['genetics'] },
      { char: '🔬', name: 'microscope', keywords: ['science', 'lab'] },
      { char: '🔭', name: 'telescope', keywords: ['astronomy'] },
      { char: '💊', name: 'pill', keywords: ['medicine'] },
      { char: '💉', name: 'syringe', keywords: ['vaccine', 'shot'] },
      { char: '🩺', name: 'stethoscope', keywords: ['doctor'] },
      { char: '🩹', name: 'adhesive bandage', keywords: ['plaster'] },
      { char: '📿', name: 'prayer beads' },
      { char: '🧴', name: 'lotion bottle' },
      { char: '🪒', name: 'razor', keywords: ['shave'] },
      { char: '🧳', name: 'luggage', keywords: ['suitcase', 'travel'] },
      { char: '🌂', name: 'closed umbrella' },
      { char: '☂️', name: 'umbrella', keywords: ['rain'] },
      { char: '🎒', name: 'backpack', keywords: ['school', 'bag'] },
      { char: '👓', name: 'glasses' },
      { char: '🕶️', name: 'sunglasses' },
      { char: '👔', name: 'necktie' },
      { char: '👕', name: 't-shirt', keywords: ['shirt'] },
      { char: '👖', name: 'jeans', keywords: ['pants'] },
      { char: '🧥', name: 'coat', keywords: ['jacket'] },
      { char: '👗', name: 'dress' },
      { char: '👠', name: 'high-heeled shoe' },
      { char: '👟', name: 'running shoe', keywords: ['sneaker'] },
      { char: '🧢', name: 'billed cap', keywords: ['hat'] },
      { char: '👑', name: 'crown', keywords: ['king', 'queen'] },
      { char: '💍', name: 'ring', keywords: ['engagement'] },
      { char: '📚', name: 'books', keywords: ['read', 'study'] },
      { char: '📖', name: 'open book', keywords: ['read'] },
      { char: '📕', name: 'closed book' },
      { char: '📒', name: 'ledger', keywords: ['notebook'] },
      { char: '📝', name: 'memo', keywords: ['note', 'write'] },
      { char: '✏️', name: 'pencil', keywords: ['write'] },
      { char: '🖊️', name: 'pen', keywords: ['write'] },
      { char: '🖌️', name: 'paintbrush' },
      { char: '🖍️', name: 'crayon' },
      { char: '📌', name: 'pushpin', keywords: ['pin'] },
      { char: '📎', name: 'paperclip', keywords: ['attach'] },
      { char: '📏', name: 'straight ruler', keywords: ['measure'] },
      { char: '✂️', name: 'scissors', keywords: ['cut'] },
      { char: '🗑️', name: 'wastebasket', keywords: ['trash', 'delete'] },
      { char: '📦', name: 'package', keywords: ['box', 'parcel', 'shipping'] },
      { char: '📬', name: 'open mailbox with raised flag', keywords: ['mail'] },
      { char: '✉️', name: 'envelope', keywords: ['mail', 'email'] },
      { char: '📮', name: 'postbox', keywords: ['mail'] },
      { char: '📅', name: 'calendar', keywords: ['date'] },
      { char: '📆', name: 'tear-off calendar', keywords: ['date'] },
      { char: '📊', name: 'bar chart', keywords: ['graph', 'stats'] },
      { char: '📈', name: 'chart increasing', keywords: ['growth', 'up'] },
      { char: '📉', name: 'chart decreasing', keywords: ['loss', 'down'] },
      { char: '🗂️', name: 'card index dividers', keywords: ['files'] },
      { char: '📁', name: 'file folder', keywords: ['folder'] },
      { char: '📄', name: 'page facing up', keywords: ['document'] },
      { char: '📰', name: 'newspaper', keywords: ['news'] },
      { char: '🔍', name: 'magnifying glass tilted left', keywords: ['search', 'find'] },
      { char: '🔎', name: 'magnifying glass tilted right', keywords: ['search'] },
      { char: '🔔', name: 'bell', keywords: ['notification'] },
      { char: '🔕', name: 'bell with slash', keywords: ['mute'] },
      { char: '📢', name: 'loudspeaker', keywords: ['announce'] },
      { char: '📣', name: 'megaphone', keywords: ['shout'] },
    ],
  },
  {
    key: 'symbols',
    label: 'Symbols',
    emojis: [
      { char: '❤️', name: 'red heart', keywords: ['love'] },
      { char: '✅', name: 'check mark button', keywords: ['done', 'yes', 'ok'] },
      { char: '❌', name: 'cross mark', keywords: ['no', 'wrong'] },
      { char: '❎', name: 'cross mark button', keywords: ['no'] },
      { char: '⭕', name: 'hollow red circle' },
      { char: '✔️', name: 'check mark', keywords: ['done'] },
      { char: '☑️', name: 'check box with check', keywords: ['done'] },
      { char: '➕', name: 'plus', keywords: ['add'] },
      { char: '➖', name: 'minus', keywords: ['subtract'] },
      { char: '➗', name: 'divide' },
      { char: '✖️', name: 'multiply' },
      { char: '♾️', name: 'infinity' },
      { char: '❓', name: 'question mark' },
      { char: '❔', name: 'white question mark' },
      { char: '❗', name: 'exclamation mark' },
      { char: '‼️', name: 'double exclamation mark' },
      { char: '⁉️', name: 'exclamation question mark' },
      { char: '⚠️', name: 'warning', keywords: ['caution', 'alert'] },
      { char: '🚫', name: 'prohibited', keywords: ['no', 'forbidden'] },
      { char: '⛔', name: 'no entry', keywords: ['stop'] },
      { char: '🔞', name: 'no one under eighteen' },
      { char: '☢️', name: 'radioactive' },
      { char: '☣️', name: 'biohazard' },
      { char: '♻️', name: 'recycling symbol', keywords: ['recycle'] },
      { char: '⚜️', name: 'fleur-de-lis' },
      { char: '🔱', name: 'trident emblem' },
      { char: '📛', name: 'name badge' },
      { char: '🔰', name: 'Japanese symbol for beginner' },
      { char: '⚕️', name: 'medical symbol' },
      { char: '♈', name: 'Aries', keywords: ['zodiac'] },
      { char: '♉', name: 'Taurus', keywords: ['zodiac'] },
      { char: '♊', name: 'Gemini', keywords: ['zodiac'] },
      { char: '♋', name: 'Cancer', keywords: ['zodiac'] },
      { char: '♌', name: 'Leo', keywords: ['zodiac'] },
      { char: '♍', name: 'Virgo', keywords: ['zodiac'] },
      { char: '♎', name: 'Libra', keywords: ['zodiac'] },
      { char: '♏', name: 'Scorpio', keywords: ['zodiac'] },
      { char: '♐', name: 'Sagittarius', keywords: ['zodiac'] },
      { char: '♑', name: 'Capricorn', keywords: ['zodiac'] },
      { char: '♒', name: 'Aquarius', keywords: ['zodiac'] },
      { char: '♓', name: 'Pisces', keywords: ['zodiac'] },
      { char: '⛎', name: 'Ophiuchus', keywords: ['zodiac'] },
      { char: '🔀', name: 'shuffle tracks button', keywords: ['random'] },
      { char: '🔁', name: 'repeat button', keywords: ['loop'] },
      { char: '🔂', name: 'repeat single button' },
      { char: '▶️', name: 'play button', keywords: ['play'] },
      { char: '⏸️', name: 'pause button', keywords: ['pause'] },
      { char: '⏹️', name: 'stop button', keywords: ['stop'] },
      { char: '⏺️', name: 'record button', keywords: ['record'] },
      { char: '⏭️', name: 'next track button', keywords: ['skip'] },
      { char: '⏮️', name: 'last track button', keywords: ['previous'] },
      { char: '⏩', name: 'fast-forward button' },
      { char: '⏪', name: 'fast reverse button' },
      { char: '🔼', name: 'upwards button', keywords: ['up'] },
      { char: '🔽', name: 'downwards button', keywords: ['down'] },
      { char: '🔺', name: 'red triangle pointed up' },
      { char: '🔻', name: 'red triangle pointed down' },
      { char: '📶', name: 'antenna bars', keywords: ['signal'] },
      { char: '📳', name: 'vibration mode' },
      { char: '📴', name: 'mobile phone off' },
      { char: '♀️', name: 'female sign' },
      { char: '♂️', name: 'male sign' },
      { char: '⚧️', name: 'transgender symbol' },
      { char: '✖', name: 'multiplication sign' },
      { char: '🔴', name: 'red circle' },
      { char: '🟠', name: 'orange circle' },
      { char: '🟡', name: 'yellow circle' },
      { char: '🟢', name: 'green circle' },
      { char: '🔵', name: 'blue circle' },
      { char: '🟣', name: 'purple circle' },
      { char: '⚫', name: 'black circle' },
      { char: '⚪', name: 'white circle' },
      { char: '🟥', name: 'red square' },
      { char: '🟧', name: 'orange square' },
      { char: '🟨', name: 'yellow square' },
      { char: '🟩', name: 'green square' },
      { char: '🟦', name: 'blue square' },
      { char: '🟪', name: 'purple square' },
      { char: '⬛', name: 'black large square' },
      { char: '⬜', name: 'white large square' },
      { char: '🔶', name: 'large orange diamond' },
      { char: '🔷', name: 'large blue diamond' },
      { char: '🔸', name: 'small orange diamond' },
      { char: '🔹', name: 'small blue diamond' },
      { char: '🔘', name: 'radio button' },
      { char: '🔳', name: 'white square button' },
      { char: '🔲', name: 'black square button' },
      { char: '💠', name: 'diamond with a dot' },
      { char: '🕐', name: 'one o\'clock', keywords: ['time'] },
      { char: '🕑', name: 'two o\'clock', keywords: ['time'] },
      { char: '🕒', name: 'three o\'clock', keywords: ['time'] },
    ],
  },
  {
    key: 'flags',
    label: 'Flags',
    emojis: [
      { char: '🏁', name: 'chequered flag', keywords: ['race', 'finish'] },
      { char: '🚩', name: 'triangular flag' },
      { char: '🎌', name: 'crossed flags' },
      { char: '🏴', name: 'black flag' },
      { char: '🏳️', name: 'white flag', keywords: ['surrender'] },
      { char: '🏳️‍🌈', name: 'rainbow flag', keywords: ['pride', 'lgbt'] },
      { char: '🏴‍☠️', name: 'pirate flag', keywords: ['pirate'] },
      { char: '🇦🇷', name: 'flag Argentina', keywords: ['argentina'] },
      { char: '🇦🇺', name: 'flag Australia', keywords: ['australia'] },
      { char: '🇧🇪', name: 'flag Belgium', keywords: ['belgium'] },
      { char: '🇧🇷', name: 'flag Brazil', keywords: ['brazil'] },
      { char: '🇨🇦', name: 'flag Canada', keywords: ['canada'] },
      { char: '🇨🇭', name: 'flag Switzerland', keywords: ['switzerland'] },
      { char: '🇨🇱', name: 'flag Chile', keywords: ['chile'] },
      { char: '🇨🇳', name: 'flag China', keywords: ['china'] },
      { char: '🇨🇴', name: 'flag Colombia', keywords: ['colombia'] },
      { char: '🇩🇪', name: 'flag Germany', keywords: ['germany', 'deutschland'] },
      { char: '🇩🇰', name: 'flag Denmark', keywords: ['denmark'] },
      { char: '🇪🇸', name: 'flag Spain', keywords: ['spain', 'espana'] },
      { char: '🇪🇺', name: 'flag European Union', keywords: ['europe', 'eu'] },
      { char: '🇫🇮', name: 'flag Finland', keywords: ['finland'] },
      { char: '🇫🇷', name: 'flag France', keywords: ['france'] },
      { char: '🇬🇧', name: 'flag United Kingdom', keywords: ['uk', 'britain', 'england'] },
      { char: '🇬🇷', name: 'flag Greece', keywords: ['greece'] },
      { char: '🇮🇪', name: 'flag Ireland', keywords: ['ireland'] },
      { char: '🇮🇳', name: 'flag India', keywords: ['india'] },
      { char: '🇮🇹', name: 'flag Italy', keywords: ['italy', 'italia'] },
      { char: '🇯🇵', name: 'flag Japan', keywords: ['japan'] },
      { char: '🇰🇷', name: 'flag South Korea', keywords: ['korea'] },
      { char: '🇲🇽', name: 'flag Mexico', keywords: ['mexico'] },
      { char: '🇳🇱', name: 'flag Netherlands', keywords: ['netherlands', 'holland'] },
      { char: '🇳🇴', name: 'flag Norway', keywords: ['norway'] },
      { char: '🇳🇿', name: 'flag New Zealand', keywords: ['new', 'zealand'] },
      { char: '🇵🇪', name: 'flag Peru', keywords: ['peru'] },
      { char: '🇵🇱', name: 'flag Poland', keywords: ['poland'] },
      { char: '🇵🇹', name: 'flag Portugal', keywords: ['portugal'] },
      { char: '🇷🇴', name: 'flag Romania', keywords: ['romania'] },
      { char: '🇸🇪', name: 'flag Sweden', keywords: ['sweden'] },
      { char: '🇹🇷', name: 'flag Turkey', keywords: ['turkey'] },
      { char: '🇺🇦', name: 'flag Ukraine', keywords: ['ukraine'] },
      { char: '🇺🇸', name: 'flag United States', keywords: ['usa', 'america'] },
      { char: '🇿🇦', name: 'flag South Africa', keywords: ['south', 'africa'] },
    ],
  },
];
