import { readdirSync, readFileSync, statSync } from 'fs';
import { join, relative, sep } from 'path';

import { ROUTES } from '@/utils/routeUtils';

/**
 * EVERY PATH THE APP NAVIGATES TO IS A PATH THE ROUTER SERVES.
 *
 * Thirteen `router.push()` calls shipped pointing at screens that did not exist:
 * an @mention, a hashtag, your own profile in the sidebar, and all seven rows of
 * the privacy settings. Each one was a tap that landed on "This screen does not
 * exist".
 *
 * Expo Router can catch that — `.expo/types/router.d.ts` types `Href` as the
 * union of real routes — but it cannot catch it HERE, for two separate reasons:
 *
 *  1. That file is generated by `expo start` / `expo export` and gitignored, so
 *     on a fresh checkout (which is what CI has) every `router.push()` argument
 *     degrades to `string` and all thirteen typecheck.
 *  2. Since `app/(chat)/[username].tsx` exists, they would not be caught even
 *     WITH the generated types. A dynamic segment at the root of a group emits
 *     `` `/${SingleRoutePart<T>}${'' | `?${string}` | `#${string}`}` `` into the
 *     href union, and with `T = string` that collapses to `` `/${string}` `` —
 *     which every path starting with a slash satisfies. Measured, not assumed:
 *     with the file present, `tsc` accepts `router.push('/definitely/not/a/route')`;
 *     with it moved aside, `tsc` rejects the same line. Mention's profile routes
 *     have the same shape and the same consequence.
 *
 * So the check lives here instead, where it runs in CI on a fresh checkout and
 * does not depend on a generated file. It reads the routes off the filesystem and
 * the destinations out of the source, and compares them — the same shape as
 * `__tests__/appearanceEndpoint.test.ts`, which exists because a URL that nobody
 * served survived in the appearance store for months.
 *
 * What it cannot see: a destination that is not a literal in the call. Those are
 * covered where they are built instead — `lib/profile/handle.ts` is the only one,
 * and `__tests__/profile/handle.test.ts` covers it.
 */

const FRONTEND = join(__dirname, '..', '..');
const APP_DIR = join(FRONTEND, 'app');

/** Where a navigation call can be written. */
const SOURCE_DIRS = ['app', 'components', 'hooks', 'lib', 'utils', 'stores'];

const SOURCE_EXTENSIONS = ['.ts', '.tsx'];

/** Route files that serve no path of their own. */
const NON_ROUTE_FILES = /^(_layout|\+html|\+not-found|\+native-intent)$/;

function walk(directory: string): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(directory)) {
    const full = join(directory, entry);
    if (statSync(full).isDirectory()) {
      if (entry === '__tests__' || entry === 'node_modules') continue;
      found.push(...walk(full));
      continue;
    }
    if (SOURCE_EXTENSIONS.some((extension) => entry.endsWith(extension))) found.push(full);
  }
  return found;
}

/**
 * A path with everything that varies replaced by `:param`, so a call and a route
 * file can be compared.
 *
 * `${…}` is an interpolation in the caller; `[id]` is a dynamic segment in the
 * filename; `(chat)` is a group, which is invisible in a URL and is dropped
 * rather than replaced. A trailing `/` is not a different route.
 */
function normalise(path: string): string {
  const segments = path
    .split('?')[0]
    .split('#')[0]
    .split('/')
    .filter((segment) => segment.length > 0)
    .filter((segment) => !/^\(.*\)$/.test(segment))
    .map((segment) => {
      if (/^\[\.{3}.+\]$/.test(segment)) return ':rest';
      if (/^\[.+\]$/.test(segment)) return ':param';
      if (/\$\{[^}]*\}/.test(segment)) return ':param';
      return segment;
    });
  return `/${segments.join('/')}`;
}

/** Every path the router serves, from the files under `app/`. */
export function servedRoutes(): string[] {
  return walk(APP_DIR)
    .map((file) => relative(APP_DIR, file).split(sep).join('/'))
    .map((file) => file.replace(/\.(ts|tsx)$/, ''))
    .filter((route) => {
      const name = route.split('/').at(-1) ?? '';
      return !NON_ROUTE_FILES.test(name);
    })
    .map((route) => route.replace(/(^|\/)index$/, ''))
    .map((route) => normalise(`/${route}`));
}

/**
 * Source with its comments taken out.
 *
 * The modules that explain this routing quote `router.push(…)` in their own
 * documentation, and a scanner that read those would check the examples rather
 * than the code.
 */
function withoutComments(source: string): string {
  return source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:])\/\/.*$/gm, '$1');
}

export interface NavigationTarget {
  readonly file: string;
  readonly path: string;
}

/**
 * Every literal path handed to the router, from anywhere in the app.
 *
 * Both spellings of a destination are read: the imperative `router.push('/x')`
 * and the declarative `<Redirect href={`/x`} />`. A call whose argument is a
 * variable or a function result produces no match and is not reported — this
 * lists what can be checked, not what exists.
 */
export function navigationTargets(): NavigationTarget[] {
  const calls =
    /(?:router|navigation)\s*\.\s*(?:push|replace|navigate)\(\s*(['"`])([^'"`]*)\1/g;
  const redirects = /href=\{?\s*(['"`])([^'"`]*)\1/g;

  const targets: NavigationTarget[] = [];
  for (const directory of SOURCE_DIRS) {
    for (const file of walk(join(FRONTEND, directory))) {
      const source = withoutComments(readFileSync(file, 'utf8'));
      for (const pattern of [calls, redirects]) {
        for (const [, , path] of source.matchAll(pattern)) {
          // Only in-app paths. An external URL is somebody else's routing table.
          if (!path.startsWith('/')) continue;
          targets.push({ file: relative(FRONTEND, file), path });
        }
      }
    }
  }
  return targets;
}

function isServed(path: string, routes: ReadonlySet<string>): boolean {
  const normalised = normalise(path);
  if (routes.has(normalised)) return true;

  // A `:param` in the CALL is an interpolation, and an interpolation can carry
  // more than one segment (`/c/${a}/${b}` is written as one). Nothing does that
  // today, so an exact segment count is the strict reading and stays strict.
  return false;
}

describe('every route the app navigates to exists', () => {
  const routes = new Set(servedRoutes());
  const targets = navigationTargets();

  it('finds the routes and the destinations to compare', () => {
    // Guards the test itself. A walker or a regex that matched nothing would
    // make every assertion below vacuously true, which is the failure mode this
    // kind of test has.
    expect(routes.size).toBeGreaterThanOrEqual(15);
    expect(targets.length).toBeGreaterThanOrEqual(15);
  });

  it('serves the routes this app is built around', () => {
    expect(routes).toContain('/');
    expect(routes).toContain('/c/:param');
    expect(routes).toContain('/settings/privacy');
    expect(routes).toContain('/settings/privacy/blocked');
    // The profile segment. `[username]` sits at the root of the `(chat)` group,
    // so it normalises to a single `:param` — which is also why it doubles as
    // the catch-all for unknown one-segment paths.
    expect(routes).toContain('/:param');
  });

  it('has a screen for every path it pushes', () => {
    const missing = targets.filter((target) => !isServed(target.path, routes));

    expect(missing).toEqual([]);
  });

  it('has a screen for every route constant', () => {
    // `ROUTES` is navigated through by name rather than by literal, so the
    // scanner above cannot see its values.
    const missing = Object.entries(ROUTES).filter(([, path]) => !isServed(path, routes));

    expect(missing).toEqual([]);
  });

  it('no longer points anywhere near a search screen', () => {
    // Hashtags linked to `/search/<query>`, which has never existed here. The
    // assertion is on the whole app rather than on one file: the point is that
    // nothing anywhere routes to a search Allo does not perform.
    const searchTargets = targets.filter((target) => target.path.startsWith('/search'));

    expect(searchTargets).toEqual([]);
  });
});
